import datetime
import time
datetimenow=datetime.datetime.now()# lay ngay thang nam gio hien tai
print(datetimenow)
d=datetime.date(2012,1,1)# set ngay cho d
print(d)
datenow=datetime.date.today()
print(datenow)
print(dir(datenow))
print("*"*20)
print("this year is: ", datenow.year)
print("this month is: ", datenow.month)
print("this date is: ", datenow.day)
print(datetime.time())
print(datetime.time(1,2,3))
print(datetime.time(second=1,minute=2,hour=3))
all=datetime.datetime(2020,2,23,3,4,25,100)
print(all)
print(all.year)
print(all.month)
print(all.day)
print(all.hour)
print(all.minute)
print(all.second)
print("*"*20)
t2=datetime.datetime(2020,2,23,3,4,25,100)
t3=datetime.datetime(2020,3,23,4,3,25,100)
t4=t3-t2
print(t4)
print("*"*30)
t=datetime.datetime.now()
print(t)
k=t.strftime("%d/%m/%y : %H:%M:%S")
print(k)
print("*"*30)
print("hello boss")
time.sleep(5)
print("I'm bro at this")